package com.example.demo.entity.model;

public enum Condition {
    BLINDED, CHARMED, DEAFENED, FRIGHTENED, GRAPPLED, INCAPACITATED, INVISIBLE, PARALYZED, PETRIFIED, POISONED,
    PRONE, RESTRAINED, STUNNED, UNCONSCIOUS, EXHAUSTION
}
