package com.example.demo.entity.model;

public enum Language {
    COMMON, DWARFISH, ELVISH, GIANT, GNOMISH, GOBLIN, HALFLING, ORC, ABYSSAL, CELESTIAL, DRACONIC, DEEP_SPEECH,
    INFERNAL, PRIMORDIAL, SYLVAN, UNDERCOMMON
}
