package com.example.demo.entity.model;

public enum Skill {
    ATHLETICS, ACROBATICS, SLEIGHT_OF_HAND, STEALTH, ARCANA, HISTORY, INVESTIGATION, NATURE, RELIGION, INSIGHT, MEDICINE,
    ANIMAL_HANDLING, PERCEPTION, SURVIVAL, DECEPTION, INTIMIDATION, PERFORMANCE, PERSUASION
}
